name: s3contents
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip

  # Base conda deps
  - setuptools
  - setuptools-scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel
  - pytest
  - pytest-cov

  # This project conda deps

  - pip:
    # This project pip deps
    - notebook
    - requests
    - boto3
    - s3fs
    - gcsfs
    - mock
