name: testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7]
        jupyter-version: ["6.*"]

    # We cant do this until we can specify the command on GitHub Actions
    services:
      minio:
        image: minio/minio:RELEASE.2018-06-29T02-11-29Z
        # command: server /export
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: access-key
          MINIO_SECRET_KEY: secret-key
        volumes:
          /tmp:/exports

    steps:
    - uses: actions/checkout@v2

    - name: Serve Minio
      run: |
        make minio &

    - name: Verify Minio
      run: |
        curl http://localhost:9000/

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install package
      run: |
        make build
        pip install dist/*.tar.gz
        pip freeze

    - name: Check linting
      run: |
        make check

    - name: Test with pytest
      if: always()
      run: |
        make tests
