name: testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: [3.5, 3.6, 3.7, 3.8]
        python-version: [3.7, 3.8]
        jupyter-version: ["4.*", "5.1", "5.2", "5.3", "5.4", "5.6", "5.7", "5.*", "6.*"]

    services:
      minio:
        image: minio/minio:RELEASE.2018-06-29T02-11-29Z
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: access-key
          MINIO_SECRET_KEY: secret-key

    steps:
    - name: Verify Minio
      run: |
        curl http://localhost:9000/

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install package
      run: |
        make build
        pip install dist/*.tar.gz
        pip freeze

    - name: Check linting
      run: |
        make check

    - name: Test with pytest
      if: always()
      run: |
        make test

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
